### ISSUE TITLE
ValueError: cannot reshape array of size 9840 into shape (2460,1,1)

### ISSUE THREAD

**Issue by longmalongma** [minzhang-1/PointHop2#1]
Hi,thanks for your great work,when i try to run your code,i meet this problem:ValueError: cannot reshape array of size 9840 into shape (2460,1,1)

**Comment by minzhang-1** [comment]
Where do you meet this problem and what's your parameter setting? I can run it well.

**Comment by longmalongma** [comment]
> Where do you meet this problem and what's your parameter setting? I can run it well.

Sorry for the late reply,it was my environment that was wrong before. my my preferences are the same as yours, I found I couldn't run pointhop2, out of memory, because you didn't use batch in pointhop2.

**Comment by minzhang-1** [comment]
> > Where do you meet this problem and what's your parameter setting? I can run it well.
> 
> Sorry for the late reply,it was my environment that was wrong before. my my preferences are the same as yours, I found I couldn't run pointhop2, out of memory, because you didn't use batch in pointhop2.

Yes, I may update a new version later. If you want to try now, you can reduce the threading number, but it will decrease the speed.

**Comment by longmalongma** [comment]
> > > Where do you meet this problem and what's your parameter setting? I can run it well.
> > 
> > 
> > Sorry for the late reply,it was my environment that was wrong before. my my preferences are the same as yours, I found I couldn't run pointhop2, out of memory, because you didn't use batch in pointhop2.
> 
> Yes, I may update a new version later. If you want to try now, you can reduce the threading number, but it will decrease the speed.



> > > Where do you meet this problem and what's your parameter setting? I can run it well.
> > 
> > 
> > Sorry for the late reply,it was my environment that was wrong before. my my preferences are the same as yours, I found I couldn't run pointhop2, out of memory, because you didn't use batch in pointhop2.
> 
> Yes, I may update a new version later. If you want to try now, you can reduce the threading number, but it will decrease the speed.

Thank you for your reply. I will try it, I think your research is great and original and I will study it carefully.

**Comment by minzhang-1** [comment]
> > > > Where do you meet this problem and what's your parameter setting? I can run it well.
> > > 
> > > 
> > > Sorry for the late reply,it was my environment that was wrong before. my my preferences are the same as yours, I found I couldn't run pointhop2, out of memory, because you didn't use batch in pointhop2.
> > 
> > 
> > Yes, I may update a new version later. If you want to try now, you can reduce the threading number, but it will decrease the speed.
> 
> > > > Where do you meet this problem and what's your parameter setting? I can run it well.
> > > 
> > > 
> > > Sorry for the late reply,it was my environment that was wrong before. my my preferences are the same as yours, I found I couldn't run pointhop2, out of memory, because you didn't use batch in pointhop2.
> > 
> > 
> > Yes, I may update a new version later. If you want to try now, you can reduce the threading number, but it will decrease the speed.
> 
> Thank you for your reply. I will try it, I think your research is great and original and I will study it carefully.

By the way, you can still run evaluate.py use the parameters I provide, there shouldn't be memory problem when you do testing.

**Comment by longmalongma** [comment]
> > > > > Where do you meet this problem and what's your parameter setting? I can run it well.
> > > > 
> > > > 
> > > > Sorry for the late reply,it was my environment that was wrong before. my my preferences are the same as yours, I found I couldn't run pointhop2, out of memory, because you didn't use batch in pointhop2.
> > > 
> > > 
> > > Yes, I may update a new version later. If you want to try now, you can reduce the threading number, but it will decrease the speed.
> > 
> > 
> > > > > Where do you meet this problem and what's your parameter setting? I can run it well.
> > > > 
> > > > 
> > > > Sorry for the late reply,it was my environment that was wrong before. my my preferences are the same as yours, I found I couldn't run pointhop2, out of memory, because you didn't use batch in pointhop2.
> > > 
> > > 
> > > Yes, I may update a new version later. If you want to try now, you can reduce the threading number, but it will decrease the speed.
> > 
> > 
> > Thank you for your reply. I will try it, I think your research is great and original and I will study it carefully.
> 
> By the way, you can still run evaluate.py use the parameters I provide, there shouldn't be memory problem when you do testing.

Ok, thank you again.
