### ISSUE TITLE
Why the inference time is much higher than training time?

### ISSUE THREAD

**Issue by johnnylu305** [minzhang-1/PointHop2#2]
Hello, you mentioned the inference time and training time of PointHop and PointHop++ in your paper. My question is why the inference time is much higher than training time? Why the inference time of PointHop/PointHop++ is higher than PointNet? Is this because it needs to compute PCA again for each input data during inference time?

**Comment by minzhang-1** [comment]
I am sorry that the table causes confusion. First, the training time is in hours while the inference time is in ms, you can find the description in the corresponding paragraph. Second, PointNet uses GPU while ours use CPU. If you are interested, you could use GPU for testing. I believe the inference time should be much faster but we didn't compare that in our paper. And we actually have an improved version for implementing our two works. You can find the link in readme.

**Comment by johnnylu305** [comment]
Got it. Thank you.

**Comment by johnnylu305** [comment]
Sorry, one quick question. For PointHop++, you also use cpu to train it and its training time is faster than PointNet. However, its inference time is slower than Pointnet. Do you know why? Do we need to compute PCA again during inference time?

**Comment by minzhang-1** [comment]
The faster training is because PointHop++ is a statistics-based approach rather than optimization-based approach which means you only need to train one epoch. You don't need to compute PCA again for inference.

**Comment by johnnylu305** [comment]
Thank you again.
